package dev.truedoctales.report.html;

import java.util.List;

/// Provides the HTML template and CSS styles for the Book of Truth report.
/// This separates the presentation layer from the report generation logic.
final class HtmlTemplate {

  private HtmlTemplate() {
    throw new AssertionError("Utility class should not be instantiated");
  }

  /// Generates the HTML header section.
  ///
  /// @param bookTitle the title of the book
  /// @return HTML header markup
  static String header(String bookTitle) {
    return """
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>"""
        + HtmlEscaper.escape(bookTitle)
        + """
         - Book of Truth</title>
            <style>
        """
        + CssGenerator.generateCss()
        + """
            </style>
        </head>
        <body>
            <div class="nav-overlay" onclick="toggleNavigation()"></div>
            <button class="burger-menu" onclick="toggleNavigation()" aria-label="Toggle navigation">
                <span></span>
                <span></span>
                <span></span>
            </button>
            <div class="book-container">
        """;
  }

  /// Generates the navigation sidebar.
  ///
  /// @param chapters list of navigation items representing chapters and their stories
  /// @return HTML navigation markup
  static String navigation(List<NavigationItem> chapters) {
    StringBuilder nav = new StringBuilder();
    nav.append(
        """
                <nav class="navigation">
                    <h2>📑 Table of Contents</h2>
        """);

    for (NavigationItem chapter : chapters) {
      nav.append("                    <div class=\"nav-section\">\n");
      nav.append("                        <h3 class=\"nav-chapter\">")
          .append(HtmlEscaper.escape(chapter.title()))
          .append("</h3>\n");

      if (!chapter.stories().isEmpty()) {
        nav.append("                        <ul class=\"nav-list\">\n");
        for (String story : chapter.stories()) {
          String storyId = sanitizeId(chapter.title() + "-" + story);
          nav.append("                            <li><a href=\"#")
              .append(storyId)
              .append("\">")
              .append(HtmlEscaper.escape(story))
              .append("</a></li>\n");
        }
        nav.append("                        </ul>\n");
      }

      nav.append("                    </div>\n");
    }

    nav.append(
        """
                </nav>
        """);
    return nav.toString();
  }

  /// Generates the main content area opening.
  ///
  /// @param timestamp the timestamp when the report was generated
  /// @return HTML content start markup
  static String contentStart(String timestamp) {
    return """
                <main class="content">
                    <div class="page-header">
                        <h1>📖 Book of Truth</h1>
                        <div class="timestamp">Generated:\s"""
        + timestamp
        + """
                        </div>
                    </div>
        """;
  }

  /// Generates the main content area closing.
  ///
  /// @return HTML content end markup
  static String contentEnd() {
    return """
                </main>
            </div>
        """;
  }

  /// Generates the HTML footer with JavaScript.
  ///
  /// @return HTML footer markup including scripts
  static String footer() {
    return """
            <footer>
                <p>Generated by True Doc Tales Testing Framework</p>
                <p>Book of Truth - A comprehensive report of all test executions</p>
            </footer>
            <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
            <script>
                // Initialize Mermaid for diagrams
                mermaid.initialize({
                    startOnLoad: true,
                    theme: 'default',
                    flowchart: {
                        useMaxWidth: true,
                        htmlLabels: true,
                        curve: 'basis'
                    }
                });

                // Toggle navigation visibility
                function toggleNavigation() {
                    const nav = document.querySelector('.navigation');
                    const burger = document.querySelector('.burger-menu');
                    const overlay = document.querySelector('.nav-overlay');
                    nav.classList.toggle('open');
                    burger.classList.toggle('open');
                    overlay.classList.toggle('active');
                }

                // Close navigation
                function closeNavigation() {
                    const nav = document.querySelector('.navigation');
                    const burger = document.querySelector('.burger-menu');
                    const overlay = document.querySelector('.nav-overlay');
                    if (nav.classList.contains('open')) {
                        nav.classList.remove('open');
                        burger.classList.remove('open');
                        overlay.classList.remove('active');
                    }
                }

                // Story navigation
                let currentStoryIndex = 0;
                let allStories = [];

                function initializeStoryNavigation() {
                    // Collect all story elements
                    allStories = Array.from(document.querySelectorAll('.story'));
                    if (allStories.length === 0) return;

                    // Handle hash navigation
                    if (window.location.hash) {
                        navigateToStoryById(window.location.hash.substring(1));
                    }
                }

                function navigateToStory(index) {
                    if (index < 0 || index >= allStories.length) return;

                    // Show new story
                    currentStoryIndex = index;
                    const targetStory = allStories[currentStoryIndex];
                    targetStory.querySelector('detales').open = true;

                    // Scroll to story
                    targetStory.scrollIntoView({ behavior: 'smooth', block: 'start' });

                    // Update URL hash
                    window.location.hash = targetStory.id;

                    // Close navigation after clicking a link
                    closeNavigation();
                }

                function navigateToStoryById(storyId) {
                    const index = allStories.findIndex(story => story.id === storyId);
                    if (index !== -1) {
                        navigateToStory(index);
                    }
                }

                // Navigation link handling
                document.addEventListener('DOMContentLoaded', function() {
                    initializeStoryNavigation();

                    // Add click handlers to navigation links
                    document.querySelectorAll('.nav-list a').forEach(link => {
                        link.addEventListener('click', function(e) {
                            e.preventDefault();
                            const targetId = this.getAttribute('href').substring(1);
                            navigateToStoryById(targetId);
                        });
                    });
                });

                // Handle browser back/forward buttons
                window.addEventListener('hashchange', function() {
                    if (window.location.hash) {
                        navigateToStoryById(window.location.hash.substring(1));
                    }
                });
            </script>
        </body>
        </html>
        """;
  }

  /// Sanitizes text to create a valid HTML ID.
  ///
  /// @param text the text to sanitize
  /// @return sanitized ID string with only lowercase letters, numbers, and hyphens
  static String sanitizeId(String text) {
    return text.toLowerCase().replaceAll("[^a-z0-9]+", "-").replaceAll("^-|-$", "");
  }

  /// Navigation item for building the table of contents.
  ///
  /// @param title the chapter title
  /// @param stories list of story titles in this chapter
  record NavigationItem(String title, List<String> stories) {}
}
